<?php
/**
 * HazmatTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ebay\Sell\Inventory
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * OpenAPI spec version: 1.17.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ebay\Sell\Inventory;

use PHPUnit\Framework\TestCase;

/**
 * HazmatTest Class Doc Comment
 *
 * @category    Class
 * @description This container is used by the seller to provide hazardous material information for the listing.&lt;br&gt;&lt;br&gt;Three elements are required to complete the Hazmat section of a listing:&lt;ul&gt;&lt;li&gt;&lt;b&gt;Pictograms&lt;/b&gt;&lt;/li&gt;&lt;li&gt;&lt;b&gt;SignalWord&lt;/b&gt;&lt;/li&gt;&lt;li&gt;&lt;b&gt;Statements&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;&lt;br&gt;A fourth element, &lt;b&gt;Component&lt;/b&gt;, is optional.
 * @package     Ebay\Sell\Inventory
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HazmatTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Hazmat"
     */
    public function testHazmat()
    {
    }

    /**
     * Test attribute "component"
     */
    public function testPropertyComponent()
    {
    }

    /**
     * Test attribute "pictograms"
     */
    public function testPropertyPictograms()
    {
    }

    /**
     * Test attribute "signal_word"
     */
    public function testPropertySignalWord()
    {
    }

    /**
     * Test attribute "statements"
     */
    public function testPropertyStatements()
    {
    }
}
